=== the42potato/AllAdultsHere/static/dist/src/json/schema/recipes.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Recipe",
    "type": "object",
    "required": ["title", "meal_type", "prep_type", "total_prep_time_minutes", "servings", "ingredients", "instructions"],
    "properties": {
        "title": {
        "type": "string"
        },
        "source": {
            "type": "object",
            "required": ["href", "displaytext"],
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri"
                },
                "displaytext": {
                    "type": "string"
                }
            }
        },
        "meal_type": {
            "oneOf": [
                {
                    "type": "string",
                    "enum": ["breakfast", "lunch", "dinner", "dessert", "side"]
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["breakfast", "lunch", "dinner", "dessert", "side"]
                    },
                    "minItems": 1
                }
            ]
        },
        "prep_type": {
            "oneOf": [
                {
                    "type": "string",
                    "enum": ["stovetop", "oven", "grill", "crock-pot", "microwave", "no-cook"]
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["stovetop", "oven", "grill", "crock-pot", "microwave", "no-cook"]
                    },
                    "minItems": 1
                }
            ]
        },
        "total_prep_time_minutes": {
            "oneOf": [
                {
                    "type": "integer",
                    "minimum": 1
                },
                {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 2,
                    "maxItems": 2
                }
            ]
        },
        "ingredient_prep_time_minutes": {
            "oneOf": [
                {
                    "type": "integer",
                    "minimum": 1
                },
                {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 2,
                    "maxItems": 2
                }
            ]
        },
        "cook_time_minutes": {
            "oneOf": [
                {
                    "type": "integer",
                    "minimum": 1
                },
                {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 2,
                    "maxItems": 2
                }
            ]
        },
        "tags": {
            "oneOf": [
                {
                    "type": "string",
                    "enum": ["minimal-dishes"]
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["minimal-dishes"]
                    },
                    "minItems": 1
                }
            ]
        },
        "goes_with": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["displaytext", "json_filename"],
                    "properties": {
                        "displaytext": { "type": "string" },
                        "json_filename": {
                            "type": "string",
                            "pattern": "^[a-z_]+$"
                        }
                    },
                    "additionalProperties": false
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "required": ["displaytext", "json_filename"],
                        "properties": {
                            "displaytext": { "type": "string" },
                            "json_filename": {
                                "type": "string",
                                "pattern": "^[a-z_]+$"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            ]
        },
        "servings": {
            "oneOf": [
                {
                    "type": "integer",
                    "minimum": 1
                },
                {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 2,
                    "maxItems": 2
                }
            ]
        },
        "ingredients": {
        "type": "array",
        "items": { "type": "string" }
        },
        "equipment": {
        "type": "array",
        "items": { "type": "string" }
        },
        "instructions": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["text"],
                    "properties": {
                        "text": { "type": "string" },
                        "bold": { "type": "boolean", "default": false },
                        "italic": { "type": "boolean", "default": false },
                        "measurement": { "type": "boolean", "default": false },
                        "timescale": { "type": "boolean", "default": false },
                        "temperature": { "type": "boolean", "default": false },
                        "href": {
                            "type": "string",
                            "format": "uri",
                            "default": null
                        }
                    }
                }
            }
        },
        "notes": {
            "type": "array",
            "items": { "type": "string" }
        }
    }
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/sweet_potato_fries.json
{
    "title": "Sweet Potato Fries",
    "source": {
        "href": "https://www.delish.com/cooking/recipe-ideas/a45105079/baked-sweet-potato-fries-recipe/",
        "displaytext": "Delish"
    },
    "meal_type": ["side"],
    "prep_type": "oven",
    "total_prep_time_minutes": [50, 60],
    "ingredient_prep_time_minutes": 10,
    "cook_time_minutes": [40, 50],
    "servings": [3, 5],
    "ingredients": [
        "1 3/4lbs (~6-8) sweet potatoes",
        "1 tablespoon corn starch",
        "3/5 teaspoon kosher salt",
        "1/4 teaspoon freshly ground black pepper",
        "1/4 teaspoon garlic powder",
        "1/4 teaspoon onion powder",
        "1/4 teaspoon paprika",
        "2 tablespoon olive oil",
        "Flaky sea salt"
    ],
    "equipment": [
        "2 cooking sheets",
        "Mixing bowl",
        "Small bowl",
        "Cooking spray",
        "Spatula"
    ],
    "instructions": [
        [
            {"text": "Arrange the racks in the upper and lower thirds of the oven. Preheat to 425F."}
        ],
        [
            {"text": "Cut sweet potatoes lengthwise. Cut halves into 1/4-inch fries. Transfer to bowl."}
        ],
        [
            {"text": "Mix corn starch, kosher salt, pepper, garlic powder, onion powder, and paprika in a small bowl. Mix and sprinkle over potatoes. Toss with hands until coated, then slowly add oil."}
        ],
        [
            {"text": "Spray cooking sheets and arrange potatoes in a single layer. Leave space around each piece."}
        ],
        [
            {"text": "Bake 25 minutes, flip, and bake 25 again until browned and fragrant. Sprinkle with sea salt after removing to ensure it sticks. Let cool 5 minutes."}
        ]
    ]
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/potato_and_leek_soup.json
{
    "title": "Potato and Leek Soup",
    "source": {
        "href": "http://www.sweetsugarbean.com/2011/10/#:~:text=Cheesy%20Bacon%2C%20Potato%20and%20Leek%20Soup",
        "displaytext": "Renee Kohlman"
    },
    "meal_type": ["lunch", "dinner"],
    "prep_type": "stovetop",
    "total_prep_time_minutes": [40, 60],
    "ingredient_prep_time_minutes": [10, 20],
    "cook_time_minutes": [30, 40],
    "servings": [4, 6],
    "ingredients": [
        "2 tablespoons butter",
        "3 leeks, white part only, washed thoroughly and sliced",
        "2 cloves garlic, minced",
        "8 medium potatoes, Yukon Golds, or other white",
        "5 cups of veggie stock",
        "2 teaspoons Dijon mustard",
        "Dash of cayenne pepper",
        "Salt and pepper",
        "1 cup grated cheese, such as old cheddar or Gouda",
        "1/2 cup whipping cream",
        "1/2 cup milk"
    ],
    "equipment": [
        "Large pot",
        "Immersion blender",
        "Large spoon or ladle",
        "Knife and cutting board",
        "Measuring cups and spoons"
    ],
    "instructions": [
        [
            {"text": "Melt"},
            {"text": "2tbsp", "measurement": true},
            {"text": "of butter in pot. Add the leeks, and cook until a little bit soft, about"},
            {"text": "3 minutes.", "timescale": true}
        ],
        [
            {"text": "Add the garlic, cook a minute longer."}
        ],
        [
            {"text": "Add the potatoes and stock, and stir in the Dijon mustard and cayenne. You want the potatoes to be covered with about"},
            {"text": "an inch or so", "measurement": true},
            {"text": "of broth (this takes"},
            {"text": "~4-5 cups", "measurement": true},
            {"text": "of broth)."}
        ],
        [
            {"text": "Cover, bring to a boil, reduce heat to a simmer and cook until potatoes are soft and falling apart, about"},
            {"text": "20 minutes.", "timescale": true}
        ],
        [
            {"text": "Remove from heat. Using an immersion blender, puree until smooth."}
        ],
        [
            {"text": "Put back on low heat, stir in the cheese until melted."}
        ],
        [
            {"text": "Stir in milk and cream. Adjust seasonings with more salt, pepper, cheese and if too thick, thin out with more milk or stock."}
        ],
        [
            {"text": "Garnish with more cheese, chives, and crumbled bacon."}
        ]
    ]
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/caramelized_onion_pasta.json
{
    "title": "Caramelized Onion Pasta",
    "source": {
        "href": "https://www.howsweeteats.com/2020/09/caramelized-onion-tomato-pasta/",
        "displaytext": "HowSweetEats"
    },
    "meal_type": ["lunch", "dinner"],
    "prep_type": "stovetop",
    "total_prep_time_minutes": [45, 70],
    "ingredient_prep_time_minutes": [15, 25],
    "cook_time_minutes": [30, 45],
    "servings": [2, 4],
    "tags": ["minimal-dishes"],
    "ingredients": [
        "2 vidalia onions",
        "2 tablespoons butter",
        "1 red pepper",
        "8 ounces cavatappi pasta",
        "3 cloves garlic",
        "1-2 springs fresh basil",
        "1/4 pound parmesan cheese"
    ],
    "equipment": [
        "Skillet",
        "Pot",
        "Colander",
        "Spoon"
    ],
    "instructions": [
        [
            {"text": "Cut onion into julienne strips. Dice garlic. Chop basil. Cut pepper."}
        ],
        [
            {"text": "Melt butter on skillet and add onion. Cook on medium heat with salt and pepper for 25-35 minutes until onions are golden and caramely."}
        ],
        [
            {"text": "Near end of onion cooking, bring a pot of salted water to boil. Cook pasta and drain."}
        ],
        [
            {"text": "Add garlic and peppers to skillet with onion. Cook until peppers brown slightly (5-10 minutes)."}
        ],
        [
            {"text": "Add pasta, basil, and parmesan to skillet. Cook until cheese melted, than another couple minutes."}
        ],
        [
            {"text": "Top with more basil and parmesan, and serve."}
        ]
    ],
    "notes": [
        "The original recipe contained tomatoes. I wasn't a fan in this dish, but peppers are pretty good!"
    ]
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/one_pot_tomato_basil_pasta.json
{
    "title": "One-Pot Tomato Basil Pasta",
    "meal_type": ["lunch", "dinner"],
    "prep_type": "stovetop",
    "total_prep_time_minutes": [25, 35],
    "ingredient_prep_time_minutes": [10, 15],
    "cook_time_minutes": [15, 20],
    "servings": [4, 6],
    "tags": ["minimal-dishes"],
    "ingredients": [
        "16oz linguine pasta",
        "1 can (14.5oz) diced tomatoes, undrained",
        "1 large vidalia onion",
        "4 cloves garlic",
        "1/2-1 teaspoon red pepper flakes",
        "2 teaspoons dried oregano",
        "2 large springs of basil",
        "4.5 cups vegetable broth",
        "2 tablespoons olive oil",
        "Parmesan cheese for garnish"
    ],
    "equipment": [
        "Large stock pot",
        "Large spoon or ladle",
        "Knife and cutting board",
        "Measuring cups and spoons"
    ],
    "instructions": [
        [
            {"text": "Peel onion and cut into julienne strips, mince garlic, and chop basil."}
        ],
        [
            {"text": "Place pasta, tomatoes, onion, garlic, basil, in a large stock pot. Optionally, cut the pasta in half first."}
        ],
        [
            {"text": "Pour in vegetable broth. Sprinkle on top the pepper flakes and oregano. Drizzle top with oil."}
        ],
        [
            {"text": "Cover pot and bring to a boil. Reduce to a low simmer and keep covered and cook for about"},
            {"text": "10 minutes", "timescale": true},
            {"text": "and stirring every"},
            {"text": "2 minutes", "timescale": true},
            {"text": "or so. Cook until almost all liquid has evaporated"},
            {"text": "(around", "italic": true},
            {"text": "1 inch", "measurement": true, "italic": true},
            {"text": "remaining at bottom of pot).", "italic": true}
        ],
        [
            {"text": "Season to taste with salt and pepper , stirring pasta several times to distribute the liquid in the bottom of the pot. Serve garnished with parmesan cheese."}
        ]
    ]
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/onion_crusted_chichen.json
{
    "title": "Onion-Crusted Chicken",
    "source": {
        "href": "https://www.allrecipes.com/recipe/269078/french-fried-onions/",
        "displaytext": "AllRecipes"
    },
    "meal_type": ["lunch", "dinner"],
    "prep_type": ["stovetop", "oven"],
    "total_prep_time_minutes": [40, 60],
    "ingredient_prep_time_minutes": [20, 30],
    "cook_time_minutes": [20, 30],
    "servings": [2, 4],
    "tags": ["minimal-dishes"],
    "ingredients": [
        "6 chicken breast halves (about 1.5 lbs)",
        "1 cup dry bread crumbs.",
        "2 cups milk",
        "2 large eggs",
        "2 large yellow onions",
        "2 cups all-purpose flour",
        "Vegetable oil for frying",
        "Garlic powder to taste",
        "Onion powder to taste"
    ],
    "equipment": [
        "Large Skillet",
        "Knife",
        "Cutting board",
        "Spoon",
        "Whisk",
        "Mixing bowl",
        "Flat bowl or container",
        "Baking sheet"
    ],
    "instructions": [
        [
            {"text": "Cut onion into think julienne strips. Soak in milk for 5 minutes."}
        ],
        [
            {"text": "Combine flour, garlic powder, onion powder, black pepper, and salt in a bowl. Add some onions and toss to coat. Remove and repeat with remaining onions."}
        ],
        [
            {"text": "Heat oil in a large skillet or deep fryer. Fry onions in batches, stirring as needed, until browned (~2-3 minutes). Drain on paper towels and optionally season with salt."}
        ],
        [
            {"text": "Beat eggs in a bowl. Combine bread crumbs and at least 1/3 of onions in a small, flat container for coating. Remaining onions make a great snack."}
        ],
        [
            {"text": "Dip chicken breast in eggs, then press into bread crumb and onion mixture to coat it. Arrange on baking sheet and bake 20 minutes or until chicken is fully cooked."}
        ]
    ],
    "notes": [
        "I saw a lot of breaded chicken recipes involving pre-made french onions. But homemade is always so much better."
    ]
}

=== the42potato/AllAdultsHere/static/dist/src/json/recipes/zucchini_tots.json
{
    "title": "Zucchini Tots",
    "meal_type": ["breakfast", "lunch", "dinner"],
    "prep_type": "oven",
    "total_prep_time_minutes": [25, 35],
    "ingredient_prep_time_minutes": [10, 15],
    "cook_time_minutes": [15, 20],
    "servings": [3, 4],
    "ingredients": [
        "cooking spray",
        "1 medium zucchini",
        "1 large egg",
        "1/4 onion",
        "1/4 cup shredded cheese",
        "1/3 cup breadcrumbs",
        "Salt and pepper to taste"
    ],
    "equipment": [
        "Grater",
        "Spatula",
        "Kitchen towel",
        "Mixing bowl",
        "Baking sheet"
    ],
    "instructions": [
        [
            {"text": "Preheat oven to"},
            {"text": "400F", "temperature": true},
            {"text": "("},
            {"text": "200C", "temperature": true},
            {"text": "). Spray a baking sheet with cooking spray."}
        ],
        [
            {"text": "Grate the zucchini and squeeze out excess moisture using a clean kitchen towel."}
        ],
        [
            {"text": "In a bowl, combine all ingredients, and mix well until combined."}
        ],
        [
            {"text": "Spoon"},
            {"text": "1 tablespoon", "measurement": true},
            {"text": "of mixture into hands and shape into an oval. Place on the prepared baking sheet."}
        ],
        [
            {"text": "Bake"},
            {"text": "15-20", "timescale": true},
            {"text": "minutes, flipping halfway through, until golden brown and crispy."}
        ]
    ]
}
